export const images = {
  tabHome: require('../../assets/images/homeTab.png'),
  tabYoloPay: require('../../assets/images/yoloPayTab.png'),
  tabGenie: require('../../assets/images/genieTab.png'),
  tabBorder: require('../../assets/images/tabBorder.png'),
  bgHome: require('../../assets/images/bgHome.png'),
  headerYoloLogo: require('../../assets/images/header.png'),
  claimSample: require('../../assets/images/claimSample1.png'),
  yLogo: require('../../assets/images/y_icon.png'),
  spinBtn: require('../../assets/images/spinNow.png'),
  altBalaji: require('../../assets/images/altBalaji.png'),
  netflix: require('../../assets/images/netflix.png'),
  ducobay: require('../../assets/images/docubay.png'),
  aha: require('../../assets/images/aha.png'),
  klikk: require('../../assets/images/klikk.png'),
  hotstar: require('../../assets/images/hotstar.png'),
  sampleImage: require('../../assets/images/samplePlatformImage.png'),
  spinBanana: require('../../assets/images/banana.png'),
  spinBomb: require('../../assets/images/bomb.png'),
  spinCrown: require('../../assets/images/crown.png'),
};
